(provide 'java_mode_config)
(defun jmhodges-java-identation ()
  (setq indent-tabs-mode nil)
  (setq tab-width 2)
  )
(add-hook 'java-mode-hook 'run-coding-hook)
(add-hook 'java-mode-hook 'jmhodges-java-identation)
