(provide 'ruby_mode_config)
(setq ruby-insert-encoding-magic-comment nil)
(add-to-list 'auto-mode-alist '("Buildfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("buildfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Capfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("Vagrantfile$" . ruby-mode))
(add-to-list 'auto-mode-alist '(".irbrc$" . ruby-mode))
(add-to-list 'auto-mode-alist '("rakefile$" . ruby-mode))
